export enum TiempoPlan {
  VISITA = 'VISITA',
  DIEZ_DIAS = 'DIEZ_DIAS',
  QUINCE_DIAS = 'QUINCE_DIAS',
  UNA_SEMANA = 'UNA_SEMANA',
  DOS_SEMANAS = 'DOS_SEMANAS',
  MENSUAL = 'UN_MES',
  TRIMESTRAL = 'TRES_MESES',
  SEMESTRAL = 'SEIS_MESES',
  ANUAL = 'UN_ANIO',
  // NUEVOS
  VISITA_10 = 'VISITA_10',
  VISITA_15 = 'VISITA_15',
}
